# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'frmComputador.ui'
##
## Created by: Qt User Interface Compiler version 6.5.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QToolBar, QWidget)
import recursos_rc

class Ui_FrmComputador(object):
    def setupUi(self, FrmComputador):
        if not FrmComputador.objectName():
            FrmComputador.setObjectName(u"FrmComputador")
        FrmComputador.resize(799, 414)
        self.actionConex_o = QAction(FrmComputador)
        self.actionConex_o.setObjectName(u"actionConex_o")
        self.actionSair = QAction(FrmComputador)
        self.actionSair.setObjectName(u"actionSair")
        self.actionListar = QAction(FrmComputador)
        self.actionListar.setObjectName(u"actionListar")
        self.actionSair_2 = QAction(FrmComputador)
        self.actionSair_2.setObjectName(u"actionSair_2")
        self.action_Novo = QAction(FrmComputador)
        self.action_Novo.setObjectName(u"action_Novo")
        icon = QIcon()
        icon.addFile(u":/icones/botoes/Add.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Novo.setIcon(icon)
        self.action_Editar = QAction(FrmComputador)
        self.action_Editar.setObjectName(u"action_Editar")
        icon1 = QIcon()
        icon1.addFile(u":/icones/botoes/COPY.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Editar.setIcon(icon1)
        self.action_Salvar = QAction(FrmComputador)
        self.action_Salvar.setObjectName(u"action_Salvar")
        icon2 = QIcon()
        icon2.addFile(u":/icones/botoes/Save.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Salvar.setIcon(icon2)
        self.action_Excluir = QAction(FrmComputador)
        self.action_Excluir.setObjectName(u"action_Excluir")
        icon3 = QIcon()
        icon3.addFile(u":/icones/botoes/Minus.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Excluir.setIcon(icon3)
        self.action_Cancelar = QAction(FrmComputador)
        self.action_Cancelar.setObjectName(u"action_Cancelar")
        icon4 = QIcon()
        icon4.addFile(u":/icones/botoes/UNDO.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Cancelar.setIcon(icon4)
        self.action_Buscar = QAction(FrmComputador)
        self.action_Buscar.setObjectName(u"action_Buscar")
        icon5 = QIcon()
        icon5.addFile(u":/icones/botoes/FIND.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Buscar.setIcon(icon5)
        self.action_Inicio = QAction(FrmComputador)
        self.action_Inicio.setObjectName(u"action_Inicio")
        icon6 = QIcon()
        icon6.addFile(u":/icones/botoes/first.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Inicio.setIcon(icon6)
        self.action_Anterior = QAction(FrmComputador)
        self.action_Anterior.setObjectName(u"action_Anterior")
        icon7 = QIcon()
        icon7.addFile(u":/icones/botoes/prior.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Anterior.setIcon(icon7)
        self.action_Proximo = QAction(FrmComputador)
        self.action_Proximo.setObjectName(u"action_Proximo")
        icon8 = QIcon()
        icon8.addFile(u":/icones/botoes/next.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Proximo.setIcon(icon8)
        self.action_Fim = QAction(FrmComputador)
        self.action_Fim.setObjectName(u"action_Fim")
        icon9 = QIcon()
        icon9.addFile(u":/icones/botoes/last.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Fim.setIcon(icon9)
        self.action_Sair = QAction(FrmComputador)
        self.action_Sair.setObjectName(u"action_Sair")
        icon10 = QIcon()
        icon10.addFile(u":/icones/botoes/CLOSE1.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.action_Sair.setIcon(icon10)
        self.centralwidget = QWidget(FrmComputador)
        self.centralwidget.setObjectName(u"centralwidget")
        self.abas = QTabWidget(self.centralwidget)
        self.abas.setObjectName(u"abas")
        self.abas.setGeometry(QRect(0, 0, 791, 321))
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.abas.setFont(font)
        self.abas.setCursor(QCursor(Qt.IBeamCursor))
        self.tabCadastro = QWidget()
        self.tabCadastro.setObjectName(u"tabCadastro")
        self.label = QLabel(self.tabCadastro)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 15, 221, 21))
        self.label_2 = QLabel(self.tabCadastro)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 81, 21))
        self.edDescricao = QLineEdit(self.tabCadastro)
        self.edDescricao.setObjectName(u"edDescricao")
        self.edDescricao.setGeometry(QRect(170, 50, 421, 31))
        self.edDescricao.setMaxLength(50)
        self.edDescricao.setReadOnly(True)
        self.edCodComputador = QLineEdit(self.tabCadastro)
        self.edCodComputador.setObjectName(u"edCodComputador")
        self.edCodComputador.setGeometry(QRect(170, 10, 141, 31))
        self.edCodComputador.setMaxLength(10)
        self.edCodComputador.setReadOnly(True)
        self.chkUso = QCheckBox(self.tabCadastro)
        self.chkUso.setObjectName(u"chkUso")
        self.chkUso.setEnabled(False)
        self.chkUso.setGeometry(QRect(0, 90, 181, 20))
        self.chkUso.setLayoutDirection(Qt.RightToLeft)
        self.chkUso.setCheckable(True)
        self.chkUso.setChecked(True)
        self.btnConfirmarProcura = QPushButton(self.tabCadastro)
        self.btnConfirmarProcura.setObjectName(u"btnConfirmarProcura")
        self.btnConfirmarProcura.setEnabled(False)
        self.btnConfirmarProcura.setGeometry(QRect(320, 14, 75, 24))
        icon11 = QIcon()
        icon11.addFile(u":/icones/COPY.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.abas.addTab(self.tabCadastro, icon11, "")
        self.tabListagem = QWidget()
        self.tabListagem.setObjectName(u"tabListagem")
        self.grdComputador = QTableWidget(self.tabListagem)
        if (self.grdComputador.columnCount() < 5):
            self.grdComputador.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setBackground(QColor(255, 255, 0));
        self.grdComputador.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.grdComputador.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.grdComputador.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.grdComputador.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.grdComputador.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.grdComputador.setObjectName(u"grdComputador")
        self.grdComputador.setGeometry(QRect(10, 60, 771, 221))
        self.grdComputador.setFrameShadow(QFrame.Sunken)
        self.groupBox = QGroupBox(self.tabListagem)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(174, 0, 361, 51))
        self.groupBox.setStyleSheet(u"background-color: rgb(255, 255, 127);")
        self.rbPorCodigo = QRadioButton(self.groupBox)
        self.rbPorCodigo.setObjectName(u"rbPorCodigo")
        self.rbPorCodigo.setGeometry(QRect(10, 20, 91, 17))
        self.rbPorCodigo.setChecked(True)
        self.rbPorDescricao = QRadioButton(self.groupBox)
        self.rbPorDescricao.setObjectName(u"rbPorDescricao")
        self.rbPorDescricao.setGeometry(QRect(115, 20, 111, 20))
        self.rbPorCondicao = QRadioButton(self.groupBox)
        self.rbPorCondicao.setObjectName(u"rbPorCondicao")
        self.rbPorCondicao.setGeometry(QRect(241, 20, 111, 20))
        icon12 = QIcon()
        icon12.addFile(u":/icones/WINPREV.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.abas.addTab(self.tabListagem, icon12, "")
        FrmComputador.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(FrmComputador)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 799, 22))
        self.menuCadastro = QMenu(self.menubar)
        self.menuCadastro.setObjectName(u"menuCadastro")
        self.menuListagem = QMenu(self.menubar)
        self.menuListagem.setObjectName(u"menuListagem")
        self.menuSair = QMenu(self.menubar)
        self.menuSair.setObjectName(u"menuSair")
        FrmComputador.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(FrmComputador)
        self.statusbar.setObjectName(u"statusbar")
        FrmComputador.setStatusBar(self.statusbar)
        self.tbBotoes = QToolBar(FrmComputador)
        self.tbBotoes.setObjectName(u"tbBotoes")
        self.tbBotoes.setOrientation(Qt.Horizontal)
        self.tbBotoes.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        FrmComputador.addToolBar(Qt.TopToolBarArea, self.tbBotoes)

        self.menubar.addAction(self.menuCadastro.menuAction())
        self.menubar.addAction(self.menuListagem.menuAction())
        self.menubar.addAction(self.menuSair.menuAction())
        self.menuCadastro.addAction(self.actionConex_o)
        self.menuCadastro.addSeparator()
        self.menuCadastro.addAction(self.actionSair)
        self.menuListagem.addAction(self.actionListar)
        self.menuSair.addAction(self.actionSair_2)
        self.tbBotoes.addAction(self.action_Inicio)
        self.tbBotoes.addAction(self.action_Anterior)
        self.tbBotoes.addAction(self.action_Proximo)
        self.tbBotoes.addAction(self.action_Fim)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Buscar)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Novo)
        self.tbBotoes.addAction(self.action_Editar)
        self.tbBotoes.addAction(self.action_Salvar)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Cancelar)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Excluir)
        self.tbBotoes.addSeparator()
        self.tbBotoes.addAction(self.action_Sair)

        self.retranslateUi(FrmComputador)

        self.abas.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(FrmComputador)
    # setupUi

    def retranslateUi(self, FrmComputador):
        FrmComputador.setWindowTitle(QCoreApplication.translate("FrmComputador", u"Manuten\u00e7\u00e3o de Computadores", None))
#if QT_CONFIG(tooltip)
        FrmComputador.setToolTip(QCoreApplication.translate("FrmComputador", u"Cadastro de computadores", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        FrmComputador.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.actionConex_o.setText(QCoreApplication.translate("FrmComputador", u"Conex\u00e3o", None))
        self.actionSair.setText(QCoreApplication.translate("FrmComputador", u"Sair", None))
        self.actionListar.setText(QCoreApplication.translate("FrmComputador", u"Listar", None))
        self.actionSair_2.setText(QCoreApplication.translate("FrmComputador", u"Sair", None))
        self.action_Novo.setText(QCoreApplication.translate("FrmComputador", u"&Novo", None))
#if QT_CONFIG(tooltip)
        self.action_Novo.setToolTip(QCoreApplication.translate("FrmComputador", u"Incluir novo registro", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Novo.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.action_Editar.setText(QCoreApplication.translate("FrmComputador", u"&Editar", None))
#if QT_CONFIG(tooltip)
        self.action_Editar.setToolTip(QCoreApplication.translate("FrmComputador", u"Altera dados do registro em exibi\u00e7\u00e3o", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Editar.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.action_Salvar.setText(QCoreApplication.translate("FrmComputador", u"&Salvar", None))
#if QT_CONFIG(tooltip)
        self.action_Salvar.setToolTip(QCoreApplication.translate("FrmComputador", u"Grava o registro atual no banco de dados", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Salvar.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_Excluir.setText(QCoreApplication.translate("FrmComputador", u"E&xcluir", None))
#if QT_CONFIG(tooltip)
        self.action_Excluir.setToolTip(QCoreApplication.translate("FrmComputador", u"Exclui o registro exibido na tela", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Excluir.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_Cancelar.setText(QCoreApplication.translate("FrmComputador", u"&Cancelar", None))
#if QT_CONFIG(tooltip)
        self.action_Cancelar.setToolTip(QCoreApplication.translate("FrmComputador", u"Cancela a opera\u00e7\u00e3o atualmente em execu\u00e7\u00e3o", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Cancelar.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.action_Buscar.setText(QCoreApplication.translate("FrmComputador", u"&Buscar", None))
#if QT_CONFIG(tooltip)
        self.action_Buscar.setToolTip(QCoreApplication.translate("FrmComputador", u"Busca o registro cujo c\u00f3digo foi digitado e o exibe", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Buscar.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.action_Inicio.setText(QCoreApplication.translate("FrmComputador", u"&In\u00edcio", None))
#if QT_CONFIG(tooltip)
        self.action_Inicio.setToolTip(QCoreApplication.translate("FrmComputador", u"Posiciona visualiza\u00e7\u00e3o no primeiro registro e o exibe", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Inicio.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.action_Anterior.setText(QCoreApplication.translate("FrmComputador", u"&Anterior", None))
#if QT_CONFIG(tooltip)
        self.action_Anterior.setToolTip(QCoreApplication.translate("FrmComputador", u"Posiciona visualiza\u00e7\u00e3o no registro anterior ao atualmente exibido", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Anterior.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.action_Proximo.setText(QCoreApplication.translate("FrmComputador", u"&Pr\u00f3ximo", None))
#if QT_CONFIG(tooltip)
        self.action_Proximo.setToolTip(QCoreApplication.translate("FrmComputador", u"Posiciona visualiza\u00e7\u00e3o no registro seguinte ao atual", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Proximo.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.action_Fim.setText(QCoreApplication.translate("FrmComputador", u"&Fim", None))
#if QT_CONFIG(tooltip)
        self.action_Fim.setToolTip(QCoreApplication.translate("FrmComputador", u"Posiciona visualiza\u00e7\u00e3o no \u00faltimo registro e o exibe", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Fim.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.action_Sair.setText(QCoreApplication.translate("FrmComputador", u"Sai&r", None))
#if QT_CONFIG(tooltip)
        self.action_Sair.setToolTip(QCoreApplication.translate("FrmComputador", u"Fecha a conex\u00e3o, salva dados e fecha o formul\u00e1rio", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_Sair.setShortcut(QCoreApplication.translate("FrmComputador", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
#if QT_CONFIG(tooltip)
        self.abas.setToolTip(QCoreApplication.translate("FrmComputador", u"Manuten\u00e7\u00e3o de Computadores", None))
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("FrmComputador", u"C\u00f3digo do computador", None))
        self.label_2.setText(QCoreApplication.translate("FrmComputador", u"Descri\u00e7\u00e3o:", None))
        self.edDescricao.setPlaceholderText(QCoreApplication.translate("FrmComputador", u"Descri\u00e7\u00e3o do computador", None))
        self.edCodComputador.setInputMask("")
        self.edCodComputador.setPlaceholderText(QCoreApplication.translate("FrmComputador", u"C\u00f3digo do computador", None))
        self.chkUso.setText(QCoreApplication.translate("FrmComputador", u"Em condi\u00e7\u00f5es de uso?  ", None))
        self.btnConfirmarProcura.setText(QCoreApplication.translate("FrmComputador", u"Procurar", None))
        self.abas.setTabText(self.abas.indexOf(self.tabCadastro), QCoreApplication.translate("FrmComputador", u"Cadastro", None))
#if QT_CONFIG(tooltip)
        self.abas.setTabToolTip(self.abas.indexOf(self.tabCadastro), QCoreApplication.translate("FrmComputador", u"Manuten\u00e7\u00e3o dos registros de Computadores", None))
#endif // QT_CONFIG(tooltip)
        ___qtablewidgetitem = self.grdComputador.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("FrmComputador", u"C\u00f3digo", None));
        ___qtablewidgetitem1 = self.grdComputador.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("FrmComputador", u"Descri\u00e7\u00e3o", None));
        ___qtablewidgetitem2 = self.grdComputador.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("FrmComputador", u"Pode usar?", None));
        ___qtablewidgetitem3 = self.grdComputador.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("FrmComputador", u"RA com reserva", None));
        ___qtablewidgetitem4 = self.grdComputador.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("FrmComputador", u"Hor\u00e1rio reservado", None));
        self.groupBox.setTitle(QCoreApplication.translate("FrmComputador", u"Ordem", None))
        self.rbPorCodigo.setText(QCoreApplication.translate("FrmComputador", u"por C\u00f3digo", None))
        self.rbPorDescricao.setText(QCoreApplication.translate("FrmComputador", u"por Descri\u00e7\u00e3o", None))
        self.rbPorCondicao.setText(QCoreApplication.translate("FrmComputador", u"por Condi\u00e7\u00e3o", None))
        self.abas.setTabText(self.abas.indexOf(self.tabListagem), QCoreApplication.translate("FrmComputador", u"Listagem", None))
#if QT_CONFIG(tooltip)
        self.abas.setTabToolTip(self.abas.indexOf(self.tabListagem), QCoreApplication.translate("FrmComputador", u"Lista os registros de Computadores", None))
#endif // QT_CONFIG(tooltip)
        self.menuCadastro.setTitle(QCoreApplication.translate("FrmComputador", u"Cadastro", None))
        self.menuListagem.setTitle(QCoreApplication.translate("FrmComputador", u"Listagem", None))
        self.menuSair.setTitle(QCoreApplication.translate("FrmComputador", u"Sair", None))
        self.tbBotoes.setWindowTitle(QCoreApplication.translate("FrmComputador", u"toolBar", None))
#if QT_CONFIG(tooltip)
        self.tbBotoes.setToolTip(QCoreApplication.translate("FrmComputador", u"Bot\u00f5es de a\u00e7\u00e3o", None))
#endif // QT_CONFIG(tooltip)
    # retranslateUi

